pydataflow/pydataflow/books/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from books import views

app_name = 'books'

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^books/$', views.book_list, name='book_list'),
    url(r'^books/create/$', views.book_create, name='book_create'),
    url(r'^books/(?P<pk>\d+)/update/$', views.book_update, name='book_update'),
    url(r'^books/(?P<pk>\d+)/delete/$', views.book_delete, name='book_delete'),
]

pydataflow/pydataflow/pydataflow/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
# from django.conf.urls import url
from django.views.generic import RedirectView

from common import views as common_views

# from meta import views as meta_views

# kill $(ps -ef | grep 8080| awk '{print $2}')

urlpatterns = [

    # url(r'^music/', include('music.urls')),
    # url(r'^', include('music.urls')),
    # url(r'^music/', include('music.urls', namespace='music')),

    #allauth urls
    url('^', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('allauth.urls')),

    path('admin/', admin.site.urls),

    # url(r'^$', common_views.home, name='home'),
    url(r'^', include('common.urls')),
    # url(r'^$', common_views.login_user, name='login_user'),
    url(r'^common/', include(('common.urls', 'common'), namespace='common')),

    url(r'^', include('scripts.urls')),
    url(r'^scripts/', include('scripts.urls')),


    url(r'^', include('books.urls')),
    url(r'^books/', include('books.urls')),

    url(r'^', include('meta.urls')),
    url(r'^meta/', include('meta.urls')),

    url(r'^', include('book_meta.urls')),
    url(r'^book_meta/', include('book_meta.urls')),


    url(r'^', include('logview.urls')),
    url(r'^logview/', include('logview.urls')),

    # url(r'^', include('logview2.urls')),
    # url(r'^logview2/', include('logview2.urls')),


    # url(r"^meta/", include("meta.urls", namespace="meta")), #required for profile/family

    # url(r"^metadata/", include("metadata.urls", namespace="metadata")), #required for new metadata
    # url(r'^metadata/', include('metadata.urls')),
    # url(r'^', include('metadata.urls')),

    url(r'^sch/', include('sch.urls')),
    url(r'^', include('sch.urls')),
    url(r'^sch/', include('sch.urls', namespace='sch')),

    # url(r'^', include('common.urls')),
    # url(r'^music/', include('music.urls')),
    # url(r'^', include('music.urls')),
    # url(r'^music/', include('music.urls', namespace='music')),

    # path('', RedirectView.as_view(pattern_name='person_changelist'), name='hr'),
    # path('hr/', include('hr.urls')),


    # url(r'^tutorial/', include('tutorial.urls')),
    # url(r'^', include('tutorial.urls')),



]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pydataflow/pydataflow/sch/urls.py
from django.conf.urls import include, url

# from django.conf.urls import patterns,
# from django.conf.urls import *
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers
from django.urls import path

from sch import views
app_name = 'sch'

from rest_framework import routers
router = routers.DefaultRouter()
router.register(r'schedule', views.ScheduleViewSet)


urlpatterns = [
    url('^admin/', admin.site.urls),
    url('^api/', include(router.urls)),

###main function to create the cron and update the table
    url(r'^sch_delete_cron/(?P<record_id>[0-9]+)/$', views.sch_delete_cron, name='sch_delete_cron'),

    # url(r'^project/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/(?P<jobflowdetail_id>[0-9]+)/(?P<sch_type>[0-9]+)/sch_remove_cron/$', views.sch_remove_cron, name='sch_remove_cron'),

    url(r'^project/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/(?P<jobflowdetail_id>[0-9]+)/(?P<sch_type>[0-9]+)/sch_create_cron/$', views.sch_create_cron, name='sch_create_cron'),

    # # #scheudling project
    url(r'^project/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/(?P<jobflowdetail_id>[0-9]+)/(?P<sch_type>[0-9]+)/sch_wizard_generic/$', views.sch_wizard_generic, name='sch_wizard_generic'),
    #url(r'^project/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/sch_main_view/$', views.sch_main_view, name='sch_main_view'),

    url(r'schedule', views.schedule, name='schedule'),


]




# "ajax": "/api/schedule/?format=datatables",

pydataflow/pydataflow/books/models.py
from __future__ import unicode_literals

from django.db import models


class Book(models.Model):
    HARDCOVER = 1
    PAPERBACK = 2
    EBOOK = 3
    BOOK_TYPES = (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book'),
    )
    title = models.CharField(max_length=50)
    publication_date = models.DateField(blank=True, null=True)
    author = models.CharField(max_length=30, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    pages = models.IntegerField(blank=True, null=True)
    book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES, blank=True, null=True)

pydataflow/pydataflow/books/forms.py
from django import forms

from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'publication_date', 'author', 'price', 'pages', 'book_type' )

pydataflow/pydataflow/books/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template.loader import render_to_string

from .models import Book
from .forms import BookForm


def book_list(request):
    books = Book.objects.all()
    return render(request, 'books/book_list.html', {'books': books})


def save_book_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            books = Book.objects.all()
            data['html_book_list'] = render_to_string('books/includes/partial_book_list.html', {
                'books': books
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def book_create(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
    else:
        form = BookForm()
    return save_book_form(request, form, 'books/includes/partial_book_create.html')


    # return HttpResponse("Access Request Submited for the project:")

def book_update(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)
    else:
        form = BookForm(instance=book)
    return save_book_form(request, form, 'books/includes/partial_book_update.html')


def book_delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    data = dict()
    if request.method == 'POST':
        book.delete()
        data['form_is_valid'] = True
        books = Book.objects.all()
        data['html_book_list'] = render_to_string('books/includes/partial_book_list.html', {
            'books': books
        })
    else:
        context = {'book': book}
        data['html_form'] = render_to_string('books/includes/partial_book_delete.html', context, request=request)
    return JsonResponse(data)

pydataflow/pydataflow/books/templates/books/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bookstore - Simple is Better Than Complex</title>
    <link href="{% static 'books/css/bootstrap.min.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% include 'books/header.html' %}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  <!--  <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>  -->


    <!--  <script src="{% static 'books/js/jquery-3.1.1.min.js' %}"></script> -->
    <script src="{% static 'bootstrap-3.3.6/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'books/js/bootstrap.min.js' %}"></script>




    {% block javascript %}
    {% endblock %}
  </body>
</html>

pydataflow/pydataflow/books/templates/books/book_list.html
{% extends 'books/base.html' %}

{% load static %}

{% block javascript %}
  <script src="{% static 'books/js/books.js' %}"></script>
  <!-- <script src="{% static 'book/js/books.js' %}"></script>  -->
{% endblock %}

{% block content %}
  <h1 class="page-header">Books</h1>

  <p>
    <button type="button" class="btn btn-primary js-create-book" data-url="{% url 'books:book_create' %}">
      <span class="glyphicon glyphicon-plus"></span>
      New book
    </button>
  </p>

  <table class="table" id="book-table">
    <thead>
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Author</th>
        <th>Type</th>
        <th>Publication date</th>
        <th>Pages</th>
        <th>Price</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% include 'books/includes/partial_book_list.html' %}
    </tbody>
  </table>

  <div class="modal fade" id="modal-book">
    <div class="modal-dialog">
      <div class="modal-content">

      </div>
    </div>
  </div>
{% endblock %}

pydataflow/pydataflow/books/templates/books/header.html
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'books:home' %}">Bookstore</a>
    </div>
    <div class="collapse navbar-collapse" id="main-menu">
      <ul class="nav navbar-nav">
        <li{% if request.path == '/books/' %} class="active"{% endif %}>
          <a href="{% url 'books:book_list' %}">Books</a>
        </li>
        <li><a href="https://simpleisbetterthancomplex.com">simpleisbetterthancomplex.com</a></li>
      </ul>
    </div>
  </div>
</nav>

pydataflow/pydataflow/books/templates/books/home.html
{% extends 'books/base.html' %}

{% block content %}
  <h1 class="page-header">Simple Ajax CRUD Example</h1>

  <p class="lead">See the example live clicking in the Books menu.</p>
{% endblock %}