pydataflow/pydataflow/books/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from books import views

app_name = 'books'

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^books/$', views.book_list, name='book_list'),
    url(r'^books/create/$', views.book_create, name='book_create'),
    url(r'^books/(?P<pk>\d+)/update/$', views.book_update, name='book_update'),
    url(r'^books/(?P<pk>\d+)/delete/$', views.book_delete, name='book_delete'),
]

pydataflow/pydataflow/common/urls.py
# from django.conf.urls import patterns, include, url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from common import views as common_views
from django.contrib.auth import views as auth_views
from django.contrib.auth import authenticate, login


from django.urls import path
from django.conf.urls import *
from . import views


urlpatterns = [


    ##to redirect to login page
    url(r'^admin/', admin.site.urls),
    url(r'^about_us/$', common_views.about_us, name='about_us'),
    url(r'^$', views.login_redirect, name='login_redirect'),
    url('update_domain/', common_views.update_domain, name='update_domain'),

    url(r'^profile_main_view/$', common_views.profile_main_view, name='profile_main_view'),
    url(r'^project_access_request/$', common_views.project_access_request, name='project_access_request'),
    url(r'^project_access_req_validate/$', common_views.project_access_req_validate, name='project_access_req_validate'),

    url(r'^my_project_access_status/$', views.my_project_access_status, name='my_project_access_status'),

    url(r'^project_access_status_detail/(?P<project_id>[0-9]+)/$', views.project_access_status_detail, name='project_access_status_detail'),
    url(r'^project_access_req_view/$', views.project_access_req_view, name='project_access_req_view'),
    url(r'^project_access_req_view_detail/(?P<project_id>[0-9]+)/$', views.project_access_req_view_detail, name='project_access_req_view_detail'),
    url(r'^project_access_status_update/(?P<project_id>[0-9]+)/(?P<access_id>[0-9]+)/(?P<is_approve>[0-9]+)/$', views.project_access_status_update, name='project_access_status_update'),


    # url(r'^project/(?P<filter_by>[a-zA_Z]+)/$', views.project_filter, name='project_filter'),
    # url(r'^project_list_view/$', views.current_project_list_view, name='project_list'),

]


    ###url(r'^project_access_status/(?P<project_id>[0-9]+)/$', views.project_access_status, name='project_access_status'),
    ### url(r'^project_access_view_update/(?P<project_id>[0-9]+)/$', views.Project_accessview_update.as_view(), name='Project_accessview_update'),

###
    ### url(r'^project_access_status/$', common_views.project_access_status, name='project_access_status'),

    #tested url above
    #### url(r'^profile_main_view/$', views.profile_main_view, name='profile_main_view'),

    ###url(r'^project_list_view1/$', views.current_project_list_view1, name='project_list1'),

pydataflow/pydataflow/logview/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from django.urls import include, path
from rest_framework import routers

from logview import views
app_name = 'logview'

router = routers.DefaultRouter()
router.register(r'processlog', views.ProcesslogViewSet)
router.register(r'detaillog', views.DetaillogViewSet, basename='Processlog')

urlpatterns = [
    url('^admin/', admin.site.urls),
    url('^api/', include(router.urls)),
    url('processlog', views.processlog, name='processlog'),

    url('detaillog/(?P<process_id>[0-9]+)/$', views.DetaillogViewSet.as_view({'get': 'list'})),
    url('process_detail/(?P<process_id>[0-9]+)/$', views.detaillog, name='process_detail'),


    url(r'^log_detail/(?P<record_id>[0-9]+)/$', views.log_detail, name='log_detail'),
    url(r'^kill_process/(?P<process_id>[0-9]+)/(?P<record_id>[0-9]+)/(?P<pid>[0-9]+)/$', views.kill_process, name='kill_process'),

]

        # url('detaillog/(?P<process_id>[0-9]+)/$', views.DetaillogViewSet, name='detaillog'),

    # url('detaillog/$', views.DetaillogViewSet.as_view({'get': 'list'}), name='detaillog'),
    #url('^detaillog/(?P<process_id>[0-9]+)/$', views.DetaillogViewSet.as_view({'get': 'list'})),


    # url('tmp/(?P<process_id>[0-9]+)/$', views.detaillog, name='tmp'),

    # url('detaillog/(?P<process_id>[0-9]+)/$', views.DetaillogViewSet.as_view({'get': 'list'}), name='detaillog'),
    # url('detaillog/(?P<process_id>[0-9]+)/$', views.DetaillogViewSet.as_view(), name='detaillog'),
    # url('tmp/(?P<process_id>[0-9]+)/$', views.DetaillogViewSet.as_view({'get': 'list'}), name='tmp'),

pydataflow/pydataflow/meta/urls.py
from django.conf.urls import include, url
# from django.conf.urls import patterns
from django.conf.urls import *
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

from django.contrib import admin
from rest_framework import routers
from meta import views

router = routers.DefaultRouter()

router.register(r'projecjobflowdetailtobjects',
                views.ProjectJobflowdetailViewSet)
router.register(r'projecspnameobjects', views.ProjectSpnameViewSet)

# router.register(r'processlog', views.ProcesslogViewSet)
# router.register(r'detaillog', views.DetaillogViewSet, basename='Processlog')


# router.register(r'projecthistorytobjects', views.ProjectHistorylViewSet)

# from meta import views as meta_views
app_name = 'meta'

# # http://127.0.0.1:8000/accounts/password/reset/ not working

urlpatterns = [
    # url('project_history', views.project_history, name='project_history'),
    # url('projecthistorytobjects', views.projecthistorytobjects, name='projecthistorytobjects'),

    # url(r'^test/$', views.test, name='test'),


    url('^admin/', admin.site.urls),
    url('^api/', include(router.urls)),

    url('advance_search', views.advance_search, name='advance_search'),
    url('projecjobflowdetailtobjects', views.projecjobflowdetailtobjects,
        name='projecjobflowdetailtobjects'),
    url('projecspnameobjects', views.projecspnameobjects,
        name='projecspnameobjects'),


    # exe_jobflow_restart:
    url(r'^exe_jobflow_rerun/(?P<process_id>[0-9]+)/(?P<record_id>[0-9]+)/$',
        views.exe_jobflow_rerun, name='rerun'),

    # execute all the jobflow in the project:
    url(r'^exe_jobflow/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/$',
        views.exe_jobflow, name='exe_jobflow'),

    # exe_single_jobs_generic --> exe_jobs
    url(r'^exe_jobs/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/(?P<jobflowdetail_id>[0-9]+)/$',
        views.exe_jobs, name='exe_jobs'),



    # choose dsn and imp_object_view and delete tables
    url(r'^meta/(?P<project_id>[0-9]+)/select_src_tables/$',
        views.select_src_tables, name='select_src_tables'),
    url(r'^project/(?P<project_id>[0-9]+)/select_dsn/$',
        views.select_dsn, name='select_dsn'),
    url(r'^project/(?P<project_id>[0-9]+)/DsnTest/$',
        views.DsnTest, name='DsnTest'),

    # # # ###import & export from exported objects tables view 4 views
    url(r'^imp_sp/(?P<project_id>[0-9]+)/imp_sp/$',
        views.imp_sp, name='imp_sp'),
    url(r'^imp_sp_view/(?P<project_id>[0-9]+)/imp_sp_view/$',
        views.imp_sp_view, name='imp_sp_view'),
    url(r'^exp_sp/(?P<project_id>[0-9]+)/exp_sp/(?P<spname_id>[0-9]+)/$',
        views.exp_sp, name='exp_sp'),
    url(r'^exp_sp_view/(?P<project_id>[0-9]+)/exp_sp_view/$',
        views.exp_sp_view, name='exp_sp_view'),

    # Datasource 2 urls
    url(r'^del_dsn/(?P<project_id>[0-9]+)/(?P<datasource_id>[0-9]+)/$',
        views.del_dsn, name='del_dsn'),
    url(r'^del_dsn_view/(?P<project_id>[0-9]+)/$',
        views.del_dsn_view, name='del_dsn_view'),

    url(r'^dsn_bulk_upd/(?P<project_id>[0-9]+)/dsn_bulk_upd/$',
        views.DsnBulkUpdate.as_view(), name='dsn_bulk_update'),
    url(r'^dsn_upd/(?P<datasource_id>[0-9]+)/$',
        views.DsnUpdate.as_view(), name='dsn-update'),
    url(r'^dsn_add/(?P<project_id>[0-9]+)/$', views.dsn_add, name='dsn_add'),
    url(r'^dsn_view/(?P<project_id>[0-9]+)/dsn_view/$',
        views.DsnView, name='dsn_view'),

    # table  4 urls # # #     # delete main view     # Spname  spname_id
    url(r'^del_sp/(?P<project_id>[0-9]+)/del_sp/(?P<spname_id>[0-9]+)/$',
        views.del_sp, name='del_sp'),
    url(r'^del_sp_view/(?P<project_id>[0-9]+)/del_sp_view/$',
        views.del_sp_view, name='del_sp_view'),

    # sp bulk update####ProjectDataSourceUpdated # #     # ProjectSPBulkUpdated
    url(r'^sp_bulk_upd/(?P<project_id>[0-9]+)/$',
        views.ProjectSPBulkUpdated.as_view(), name='project-spbulk-update'),
    # reverse url to detail page
    url(r'^sp_upd/(?P<spname_id>[0-9]+)/$',
        views.SpUpdate.as_view(), name='sp_upd'),

    url(r'^sp_add/(?P<project_id>[0-9]+)/$', views.sp_add, name='sp_add'),
    url(r'^sp_detail/(\d+)/$', views.sp_detail, name='sp_detail'),

    # Projectenv variable update
    url(r'env_variables_project/(?P<project_id>[0-9]+)/$',
        views.ProjectEnvUpdated.as_view(), name='project-env-update'),

    #     ##project 3 urls
    url(r'^project_del/(?P<project_id>[0-9]+)/$',
        views.project_delete, name='project_delete'),
    url(r'^project_upd/(?P<pk>[0-9]+)/$',
        views.ProjectUpdate.as_view(), name='project_update'),
    url(r'^project_create/$', views.project_create, name='project_create'),

    url(r'^index/$', views.index, name='index'),
]


# exe_sp_util


# execute all sp
# url(r'^exe_sp_all/(?P<project_id>[0-9]+)/$', views.exe_sp_all, name='exe_sp_all'),

# get sp status
# url(r'^sp_exec_status/(?P<project_id>[0-9]+)/$', views.sp_exec_status, name='sp_exec_status'),


###url(r'^project/(?P<jobflowdetail_id>[0-9]+)/(?P<process_id>[0-9]+)/processlog_update/$', views.processlog_update, name='processlog_update'),
####url(r'^project/processlog_update/$', views.processlog_update, name='processlog_update'),
#url(r'^project/(?P<jobflowdetail_id>[0-9]+)/processlog_create/$', views.processlog_create, name='processlog_create'),
#### url(r'^project/processlog_test/$', views.processlog_test, name='processlog_test'),


# can be deleated below url
# url(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
# url(r'^project/(?P<datasource_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),


# url(r'^project/(?P<project_id>[0-9]+)/select_dsn/$', views.select_dsn, name='select_dsn'),
# url(r'^project/(?P<project_id>[0-9]+)/select_dsn1/$', views.select_dsn1, name='select_dsn1')
# url(r'^profile_setting1/(?P<project_id>[0-9]+)/profile_setting1/$', views.profile_setting1, name='profile_setting1'),

# url(r'^index1/$', views.index1, name='index1'),
# path('person/json/', views.person_json, name='person_json'),
# path('person/json2/', views.person_json2, name='person_json2'),

# url(r'^person/json2/(\d+)/$', views.person_json2, name='person_json2'),


# path('person_filter_json/json2/(?P<id>[0-9]+)/$', views.person_filter_json, name='person_filter_json'),
#path(r'^person_filter_json/json/(?P<id>[0-9]+)/$', views.person_filter_json, name='person_filter_json'),

# url(r'^table_detail2/(\d+)/$', views.table_detail2, name='table_detail2'),

# url(r'^table_detail/(\d+)/$', views.table_detail, name='table_detail'),

pydataflow/pydataflow/pydataflow/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
# from django.conf.urls import url
from django.views.generic import RedirectView

from common import views as common_views

# from meta import views as meta_views

# kill $(ps -ef | grep 8080| awk '{print $2}')

urlpatterns = [

    # url(r'^music/', include('music.urls')),
    # url(r'^', include('music.urls')),
    # url(r'^music/', include('music.urls', namespace='music')),

    #allauth urls
    url('^', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('allauth.urls')),

    path('admin/', admin.site.urls),

    # url(r'^$', common_views.home, name='home'),
    url(r'^', include('common.urls')),
    # url(r'^$', common_views.login_user, name='login_user'),
    url(r'^common/', include(('common.urls', 'common'), namespace='common')),

    url(r'^', include('scripts.urls')),
    url(r'^scripts/', include('scripts.urls')),


    url(r'^', include('books.urls')),
    url(r'^books/', include('books.urls')),

    url(r'^', include('meta.urls')),
    url(r'^meta/', include('meta.urls')),

    url(r'^', include('book_meta.urls')),
    url(r'^book_meta/', include('book_meta.urls')),


    url(r'^', include('logview.urls')),
    url(r'^logview/', include('logview.urls')),

    # url(r'^', include('logview2.urls')),
    # url(r'^logview2/', include('logview2.urls')),


    # url(r"^meta/", include("meta.urls", namespace="meta")), #required for profile/family

    # url(r"^metadata/", include("metadata.urls", namespace="metadata")), #required for new metadata
    # url(r'^metadata/', include('metadata.urls')),
    # url(r'^', include('metadata.urls')),

    url(r'^sch/', include('sch.urls')),
    url(r'^', include('sch.urls')),
    url(r'^sch/', include('sch.urls', namespace='sch')),

    # url(r'^', include('common.urls')),
    # url(r'^music/', include('music.urls')),
    # url(r'^', include('music.urls')),
    # url(r'^music/', include('music.urls', namespace='music')),

    # path('', RedirectView.as_view(pattern_name='person_changelist'), name='hr'),
    # path('hr/', include('hr.urls')),


    # url(r'^tutorial/', include('tutorial.urls')),
    # url(r'^', include('tutorial.urls')),



]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pydataflow/pydataflow/sch/urls.py
from django.conf.urls import include, url

# from django.conf.urls import patterns,
# from django.conf.urls import *
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers
from django.urls import path

from sch import views
app_name = 'sch'

from rest_framework import routers
router = routers.DefaultRouter()
router.register(r'schedule', views.ScheduleViewSet)


urlpatterns = [
    url('^admin/', admin.site.urls),
    url('^api/', include(router.urls)),

###main function to create the cron and update the table
    url(r'^sch_delete_cron/(?P<record_id>[0-9]+)/$', views.sch_delete_cron, name='sch_delete_cron'),

    # url(r'^project/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/(?P<jobflowdetail_id>[0-9]+)/(?P<sch_type>[0-9]+)/sch_remove_cron/$', views.sch_remove_cron, name='sch_remove_cron'),

    url(r'^project/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/(?P<jobflowdetail_id>[0-9]+)/(?P<sch_type>[0-9]+)/sch_create_cron/$', views.sch_create_cron, name='sch_create_cron'),

    # # #scheudling project
    url(r'^project/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/(?P<jobflowdetail_id>[0-9]+)/(?P<sch_type>[0-9]+)/sch_wizard_generic/$', views.sch_wizard_generic, name='sch_wizard_generic'),
    #url(r'^project/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/sch_main_view/$', views.sch_main_view, name='sch_main_view'),

    url(r'schedule', views.schedule, name='schedule'),


]




# "ajax": "/api/schedule/?format=datatables",

pydataflow/pydataflow/common/templates/common/breadcrum_user.html
    <div class="lr-margin content">
        <div class="breadcrumb-container">
            <div id="ember419" class="ember-view">
            <ol class="breadcrumb">

        <li User Name: <span class="badge">{{ user.username  }} </span> </li>
        <!--
            <li <a>User Name: <span class="badge">{{ user.username  }} </span></a> </li>
        -->

        <li role="presentation" class="active"><a href="{% url 'account_reset_password'  %}">Password Reset</a></li>

        {% if not request.user.is_superuser %}
        <li role="presentation" class="active"><a href="{% url 'common:project_access_request'  %}">Request Access to the Project</a></li>
        <li role="presentation" class="active"><a href="{% url 'common:my_project_access_status'  %}">My Access Status</a></li>

        {% endif %}

        <li role="presentation" class="active"><a href="{% url 'common:project_access_req_view'  %}">Approve Access Request</a></li>








        </ol>
    </div>
 </div>
</div>

pydataflow/pydataflow/common/templates/common/index.html
{# {% extends 'common/base_common.html' %} #}
{% extends 'common/base.html' %}

{% block srcsystems_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Sources -->
    <div class="row">

        {% if projects %}
            {% for project in projects %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">

<div class="caption">
    <h4>{{ project.project_name }}</h2>
   <!-- <h4>Is Active: {{ project.is_active }}</h4>  -->

    <!-- View Details -->
    <a href="{% url 'scripts:jobflow_index' project.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

    <a href="{% url 'meta:project_update' project.id %}" class="btn btn-primary btn-sm" role="button"><span class="glyphicon glyphicon-edit"></span></a>

    </div>
</div>
</div>
        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'meta:project_create' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add Project
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

<!-- If user searches and there are tables -->

</div>
{% endblock %}

pydataflow/pydataflow/common/templates/common/my_project_access_status.html
{# {% extends 'common/base_common.html' %} #}
{% extends 'common/base.html' %}

{% block srcsystems_active %}active{% endblock %}


{% block body %}

<div class="header">

{% include 'common/breadcrum_user.html' %}

</div>


<div class="albums-container container-fluid">
    <div class="row">

        {% if projects %}
            {% for project in projects %}
                <div class="col-sm-4 col-lg-3">
                    <div class="thumbnail">
                        <div class="caption">
                            <h2>{{ project.project_name }}</h2>
                            <a href="{% url 'common:project_access_status_detail' project.id %}" class="btn btn-primary btn-sm" role="button">Access Status</a>




                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <h3>No access request submited</h3>
            </div>
        {% endif %}
    </div>

</div>
{% endblock %}

pydataflow/pydataflow/common/templates/common/navbar.html
{% load staticfiles %}

<style>
#brand-image
{
  height: 25px;
}
</style>

<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
      </button>

<!--    <a class="navbar-brand" href="{% url 'about_us' %}">
      <img id="brand-image" alt="Website Logo" src="{% static 'common/images/Kaiser_Permanente.jpg' %}" />
    </a>
-->


<!--
   <a class="navbar-brand" href="{% url 'meta:index' %}">
   <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;ETL Management - PROD </a>
-->

   <a class="navbar-brand" href="{% url 'meta:index' %}">
   <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;ETL Management - Pre-PROD </a>

    </div>









<div class="collapse navbar-collapse" id="navbar" >
  <ul class="nav navbar-nav">

{% if request.user.is_authenticated %}







  <!--{% url 'common:home' as home %}  -->



  <li class=""><a href="{% url 'meta:project_create' %}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Project</a> </li>


    <form class="navbar-form navbar-left" role="search" method="get" action="#">
        <div class="form-group">
          {% if 'q' in request.GET %}
            <input type="text" class="form-control" name="q" value="{{ request.GET.q }}" placeholder="Find Project">
          {% else %}

          <input type="text" class="form-control" name="q" value="" placeholder="Find Project">

          {% endif%}
        </div>
        <button type="submit" class="btn btn-default">Search </button>
    </form>


  <li class=""><a href="{% url 'sch:schedule' %}"><span aria-hidden="true"></span>&nbsp; Schedule</a> </li>
  <li class=""><a href="{% url 'logview:processlog' %}"><span aria-hidden="true"></span>&nbsp; Logs</a> </li>

  <li class=""><a href="{% url 'meta:advance_search' %}"><span aria-hidden="true"></span>&nbsp; Advance Search</a> </li>



  </ul>
{% endif %}

    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown" >

          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"  >Account <span class="caret"></span></a>

          <ul class="dropdown-menu">

          <li><a href="{% url 'common:about_us' %}">About us</a></li>

          <li><a href="#">version 1.1</a></li>

          <li><a href="#">User: {{ user.username }}</a></li>

          <li><a href="{% url 'common:profile_main_view' %}">
          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;Settings</a></li>

          {% if not request.user.is_authenticated %}

          <li><a href="{% url 'account_login' %}">
          <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp;Login</a></li>

          <li><a href="{% url 'account_signup' %}">Signup</a></li>
          {% else %}

          <li><a href="{% url 'account_logout' %}">
          <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout</a></li>

          {% endif %}
          <!--<li class="dropdown-header">Nav header</li>
          <li><a href="#">Separated link</a></li>  -->
          </ul>
        </li>
    </ul>

</div>
</div>
</nav>

pydataflow/pydataflow/common/templates/common/project_access_req_view.html
{# {% extends 'common/base_common.html' %} #}
{% extends 'common/base.html' %}

{% block srcsystems_active %}active{% endblock %}

{% block body %}
<div class="header">

{% include 'common/breadcrum_user.html' %}

</div>


<div class="albums-container container-fluid">
    <div class="row">

        {% if projects %}
            {% for project in projects %}
                <div class="col-sm-4 col-lg-3">
                    <div class="thumbnail">
                        <div class="caption">
                            <h2>{{ project.project_name }}</h2>
                            <a href="{% url 'common:project_access_req_view_detail' project.id %}" class="btn btn-primary btn-sm" role="button">Approve Access</a>



                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <h3>No access request submited</h3>
            </div>
        {% endif %}
    </div>

</div>
{% endblock %}

pydataflow/pydataflow/common/templates/common/project_access_req_view_detail.html
{# {% extends 'common/base_common.html' %} #}
{% extends 'common/base.html' %}
{% block title %}{{ project_access }}{% endblock %}
{% block projects_active %}active{% endblock %}
{% load crispy_forms_tags %}
{% block body %}

<div class="header">

{% include 'common/breadcrum_user.html' %}

</div>

<!-- forms -->
<div class="col-sm-12 col-md-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-md-12">
                <div class="panel panel-default">
<div class="panel-body">
    <table class="table">
        <form id="form-id" method="post">
            {% csrf_token %}
            <thead>
                <tr>
                <th>Project_name</th>
                <th>Requester Email</th>
                <th>Notes</th>
                <th>Role</th>
                <th>Status</th>
                <th>access</th>
                <th>Approve/Revoke Access</th>
                </tr>
            </thead>
            <tbody>
            {% for access in project.project_access_set.all %}
                <tr>
                    <td>{{ access.project_name }}</td>
                    <td>{{ access.requester_email }}</td>
                    <td>{{ access.notes }}</td>
                    <td>{{ access.role }}</td>
                    <td>{{ access.status }}</td>
                    <td>{{ access.access }}</td>

                    <td>



        <!--<form> -->
        {% if access.access is True %}
        <!-- <input  type = "submit" value="Submit">  -->
        <a href="{% url 'common:project_access_status_update' project.id access.id 0 %}"
         class="btn btn-primary btn-sm btn-warning" role="button">Revoke Access</a>
        {% else %}
        <!--<input  type = "submit" value="Submit">  -->
        <a href="{% url 'common:project_access_status_update' project.id access.id 1 %}"
         class="btn btn-primary btn-sm btn-success" role="button">Approve Access</a>
         {% endif %}
         </form>




                </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>


            </div>
        </div>
    </div>
</div>


{% endblock %}

pydataflow/pydataflow/common/templates/common/project_access_request.html
{# {% extends 'common/base_common.html' %} #}
{% extends 'common/base.html' %}
{% block title %}{{ project }}{% endblock %}
{% block projects_active %}active{% endblock %}
{% load crispy_forms_tags %}

{% block body %}

<div class="header">

{% include 'common/breadcrum_user.html' %}

</div>


<!-- forms -->
<div class="col-sm-12 col-md-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-md-12">

                <form action="{% url 'common:project_access_req_validate' %}" method="POST" class="form">
                {% csrf_token %}

                    {{ proj_access_form.as_p }}

                <input type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}