pydataflow/pydataflow/books/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from books import views

app_name = 'books'

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^books/$', views.book_list, name='book_list'),
    url(r'^books/create/$', views.book_create, name='book_create'),
    url(r'^books/(?P<pk>\d+)/update/$', views.book_update, name='book_update'),
    url(r'^books/(?P<pk>\d+)/delete/$', views.book_delete, name='book_delete'),
]

pydataflow/pydataflow/pydataflow/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
# from django.conf.urls import url
from django.views.generic import RedirectView

from common import views as common_views

# from meta import views as meta_views

# kill $(ps -ef | grep 8080| awk '{print $2}')

urlpatterns = [

    # url(r'^music/', include('music.urls')),
    # url(r'^', include('music.urls')),
    # url(r'^music/', include('music.urls', namespace='music')),

    #allauth urls
    url('^', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('allauth.urls')),

    path('admin/', admin.site.urls),

    # url(r'^$', common_views.home, name='home'),
    url(r'^', include('common.urls')),
    # url(r'^$', common_views.login_user, name='login_user'),
    url(r'^common/', include(('common.urls', 'common'), namespace='common')),

    url(r'^', include('scripts.urls')),
    url(r'^scripts/', include('scripts.urls')),


    url(r'^', include('books.urls')),
    url(r'^books/', include('books.urls')),

    url(r'^', include('meta.urls')),
    url(r'^meta/', include('meta.urls')),

    url(r'^', include('book_meta.urls')),
    url(r'^book_meta/', include('book_meta.urls')),


    url(r'^', include('logview.urls')),
    url(r'^logview/', include('logview.urls')),

    # url(r'^', include('logview2.urls')),
    # url(r'^logview2/', include('logview2.urls')),


    # url(r"^meta/", include("meta.urls", namespace="meta")), #required for profile/family

    # url(r"^metadata/", include("metadata.urls", namespace="metadata")), #required for new metadata
    # url(r'^metadata/', include('metadata.urls')),
    # url(r'^', include('metadata.urls')),

    url(r'^sch/', include('sch.urls')),
    url(r'^', include('sch.urls')),
    url(r'^sch/', include('sch.urls', namespace='sch')),

    # url(r'^', include('common.urls')),
    # url(r'^music/', include('music.urls')),
    # url(r'^', include('music.urls')),
    # url(r'^music/', include('music.urls', namespace='music')),

    # path('', RedirectView.as_view(pattern_name='person_changelist'), name='hr'),
    # path('hr/', include('hr.urls')),


    # url(r'^tutorial/', include('tutorial.urls')),
    # url(r'^', include('tutorial.urls')),



]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pydataflow/pydataflow/sch/urls.py
from django.conf.urls import include, url

# from django.conf.urls import patterns,
# from django.conf.urls import *
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers
from django.urls import path

from sch import views
app_name = 'sch'

from rest_framework import routers
router = routers.DefaultRouter()
router.register(r'schedule', views.ScheduleViewSet)


urlpatterns = [
    url('^admin/', admin.site.urls),
    url('^api/', include(router.urls)),

###main function to create the cron and update the table
    url(r'^sch_delete_cron/(?P<record_id>[0-9]+)/$', views.sch_delete_cron, name='sch_delete_cron'),

    # url(r'^project/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/(?P<jobflowdetail_id>[0-9]+)/(?P<sch_type>[0-9]+)/sch_remove_cron/$', views.sch_remove_cron, name='sch_remove_cron'),

    url(r'^project/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/(?P<jobflowdetail_id>[0-9]+)/(?P<sch_type>[0-9]+)/sch_create_cron/$', views.sch_create_cron, name='sch_create_cron'),

    # # #scheudling project
    url(r'^project/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/(?P<jobflowdetail_id>[0-9]+)/(?P<sch_type>[0-9]+)/sch_wizard_generic/$', views.sch_wizard_generic, name='sch_wizard_generic'),
    #url(r'^project/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/sch_main_view/$', views.sch_main_view, name='sch_main_view'),

    url(r'schedule', views.schedule, name='schedule'),


]




# "ajax": "/api/schedule/?format=datatables",

pydataflow/pydataflow/books/models.py
from __future__ import unicode_literals

from django.db import models


class Book(models.Model):
    HARDCOVER = 1
    PAPERBACK = 2
    EBOOK = 3
    BOOK_TYPES = (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book'),
    )
    title = models.CharField(max_length=50)
    publication_date = models.DateField(blank=True, null=True)
    author = models.CharField(max_length=30, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    pages = models.IntegerField(blank=True, null=True)
    book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES, blank=True, null=True)

pydataflow/pydataflow/books/forms.py
from django import forms

from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'publication_date', 'author', 'price', 'pages', 'book_type' )

pydataflow/pydataflow/books/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template.loader import render_to_string

from .models import Book
from .forms import BookForm


def book_list(request):
    books = Book.objects.all()
    return render(request, 'books/book_list.html', {'books': books})


def save_book_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            books = Book.objects.all()
            data['html_book_list'] = render_to_string('books/includes/partial_book_list.html', {
                'books': books
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def book_create(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
    else:
        form = BookForm()
    return save_book_form(request, form, 'books/includes/partial_book_create.html')


    # return HttpResponse("Access Request Submited for the project:")

def book_update(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)
    else:
        form = BookForm(instance=book)
    return save_book_form(request, form, 'books/includes/partial_book_update.html')


def book_delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    data = dict()
    if request.method == 'POST':
        book.delete()
        data['form_is_valid'] = True
        books = Book.objects.all()
        data['html_book_list'] = render_to_string('books/includes/partial_book_list.html', {
            'books': books
        })
    else:
        context = {'book': book}
        data['html_form'] = render_to_string('books/includes/partial_book_delete.html', context, request=request)
    return JsonResponse(data)

pydataflow/pydataflow/books/templates/books/includes/partial_book_create.html
<form method="post" action="{% url 'books:book_create' %}" class="js-book-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a new book</h4>
  </div>
  <div class="modal-body">
    {% include 'books/includes/partial_book_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create book</button>
  </div>
</form>

pydataflow/pydataflow/books/templates/books/includes/partial_book_delete.html
<form method="post" action="{% url 'books:book_delete' book.id %}" class="js-book-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm book deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the book <strong>{{ book.title }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete book</button>
  </div>
</form>

pydataflow/pydataflow/books/templates/books/includes/partial_book_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

pydataflow/pydataflow/books/templates/books/includes/partial_book_list.html
{% for book in books %}
  <tr>
    <td>{{ book.id }}</td>
    <td>{{ book.title }}</td>
    <td>{{ book.author }}</td>
    <td>{{ book.get_book_type_display }}</td>
    <td>{{ book.publication_date }}</td>
    <td>{{ book.pages }}</td>
    <td>{{ book.price }}</td>
    <td style="width: 150px">
      <button type="button"
              class="btn btn-warning btn-sm js-update-book"
              data-url="{% url 'books:book_update' book.id %}">
        <span class="glyphicon glyphicon-pencil"></span> Edit
      </button>
      <button type="button"
              class="btn btn-danger btn-sm js-delete-book"
              data-url="{% url 'books:book_delete' book.id %}">
        <span class="glyphicon glyphicon-trash"></span> Delete
      </button>
    </td>
  </tr>
{% empty %}
  <tr>
    <td colspan="8" class="text-center bg-warning">No book</td>
  </tr>
{% endfor %}

pydataflow/pydataflow/books/templates/books/includes/partial_book_update.html
<form method="post" action="{% url 'books:book_update' form.instance.pk %}" class="js-book-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Update book</h4>
  </div>
  <div class="modal-body">
    {% include 'books/includes/partial_book_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update book</button>
  </div>
</form>