pydataflow/pydataflow/pydataflow/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
# from django.conf.urls import url
from django.views.generic import RedirectView

from common import views as common_views

# from meta import views as meta_views

# kill $(ps -ef | grep 8080| awk '{print $2}')

urlpatterns = [

    # url(r'^music/', include('music.urls')),
    # url(r'^', include('music.urls')),
    # url(r'^music/', include('music.urls', namespace='music')),

    #allauth urls
    url('^', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('allauth.urls')),

    path('admin/', admin.site.urls),

    # url(r'^$', common_views.home, name='home'),
    url(r'^', include('common.urls')),
    # url(r'^$', common_views.login_user, name='login_user'),
    url(r'^common/', include(('common.urls', 'common'), namespace='common')),

    url(r'^', include('scripts.urls')),
    url(r'^scripts/', include('scripts.urls')),


    url(r'^', include('books.urls')),
    url(r'^books/', include('books.urls')),

    url(r'^', include('meta.urls')),
    url(r'^meta/', include('meta.urls')),

    url(r'^', include('book_meta.urls')),
    url(r'^book_meta/', include('book_meta.urls')),


    url(r'^', include('logview.urls')),
    url(r'^logview/', include('logview.urls')),

    # url(r'^', include('logview2.urls')),
    # url(r'^logview2/', include('logview2.urls')),


    # url(r"^meta/", include("meta.urls", namespace="meta")), #required for profile/family

    # url(r"^metadata/", include("metadata.urls", namespace="metadata")), #required for new metadata
    # url(r'^metadata/', include('metadata.urls')),
    # url(r'^', include('metadata.urls')),

    url(r'^sch/', include('sch.urls')),
    url(r'^', include('sch.urls')),
    url(r'^sch/', include('sch.urls', namespace='sch')),

    # url(r'^', include('common.urls')),
    # url(r'^music/', include('music.urls')),
    # url(r'^', include('music.urls')),
    # url(r'^music/', include('music.urls', namespace='music')),

    # path('', RedirectView.as_view(pattern_name='person_changelist'), name='hr'),
    # path('hr/', include('hr.urls')),


    # url(r'^tutorial/', include('tutorial.urls')),
    # url(r'^', include('tutorial.urls')),



]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pydataflow/pydataflow/sch/urls.py
from django.conf.urls import include, url

# from django.conf.urls import patterns,
# from django.conf.urls import *
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers
from django.urls import path

from sch import views
app_name = 'sch'

from rest_framework import routers
router = routers.DefaultRouter()
router.register(r'schedule', views.ScheduleViewSet)


urlpatterns = [
    url('^admin/', admin.site.urls),
    url('^api/', include(router.urls)),

###main function to create the cron and update the table
    url(r'^sch_delete_cron/(?P<record_id>[0-9]+)/$', views.sch_delete_cron, name='sch_delete_cron'),

    # url(r'^project/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/(?P<jobflowdetail_id>[0-9]+)/(?P<sch_type>[0-9]+)/sch_remove_cron/$', views.sch_remove_cron, name='sch_remove_cron'),

    url(r'^project/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/(?P<jobflowdetail_id>[0-9]+)/(?P<sch_type>[0-9]+)/sch_create_cron/$', views.sch_create_cron, name='sch_create_cron'),

    # # #scheudling project
    url(r'^project/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/(?P<jobflowdetail_id>[0-9]+)/(?P<sch_type>[0-9]+)/sch_wizard_generic/$', views.sch_wizard_generic, name='sch_wizard_generic'),
    #url(r'^project/(?P<project_id>[0-9]+)/(?P<jobflow_id>[0-9]+)/sch_main_view/$', views.sch_main_view, name='sch_main_view'),

    url(r'schedule', views.schedule, name='schedule'),


]




# "ajax": "/api/schedule/?format=datatables",

pydataflow/pydataflow/meta/models.py
# # from __future__ import unicode_literals
import os
import pytz
from django.utils.timezone import activate
from django.conf import settings
from django.contrib.auth.models import Permission, User
from django.db import models
#from django.urls import reverse
from multiselectfield import MultiSelectField
# from multiselect.fields import ManyToManyField
from django.utils import timezone


# to capture the history
# from simple_history.models import HistoricalRecords

# import django_tables2 as tables

# import table

DATABASE_TYPES = (('oracle', 'oracle'), ('sqlserver', 'sqlserver'),
                  ('teradata', 'teradata'), ('mysql', 'mysql'), )


Y_N = [("Y", "Y"), ("N", "N")]

DATABASE_OBJECT_TYPES = [("Table", "Table"), ("Stored_Proc",
                                              "Stored_Proc"), ("Shell_Script", "Shell_Script")]
JOB_TYPES = (
    ('Stored_Proc', 'Stored_Proc'),
    ('Table', 'Table'),
    ('Shell_Script', 'Shell_Script'),
)


class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    project_name = models.CharField(max_length=50, unique=True)
    success_email = models.CharField(
        max_length=500, default='arjun.kumar@kp.org')
    failure_email_ind = models.BooleanField(default=False)
    failure_email = models.CharField(
        max_length=500, default='arjun.kumar@kp.org')
    is_active = models.CharField(max_length=1, choices=Y_N, default='Y')
    ## max_num_of_threads = models.SmallIntegerField(blank=False, null=False, default = 5)
    ## history = HistoricalRecords()

    def __str__(self):
        return self.project_name

    class Meta:
        ordering = ['project_name']


ROLE_TYPE = [("Master", "Master: Full Access"), ("Developer",
                                                 "Developer: Add/Edit jobs"), ("Operator", "Operator:Only Execute jobs")]


class Project_access(models.Model):
    project_name = models.ForeignKey(
        Project, on_delete=models.CASCADE, default=1)
    project_owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='project_owner', default=1)
    project_owner_email = models.EmailField(blank=True, unique=False)
    requester = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='requester', default=1)
    requester_email = models.EmailField(blank=True, unique=False)
    notes = models.CharField(
        max_length=500, default='Need access to the project to make change and execute jobs')
    role = models.CharField(max_length=10, choices=ROLE_TYPE, default='Master')
    status = models.CharField(max_length=50, default='Pending')
    access = models.BooleanField(default=False)

    def __str__(self):
        return self.project_name

    # class Meta:
    ##     ordering = ('project_name')


class DataSource(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    project_name = models.ForeignKey(
        Project, on_delete=models.CASCADE, default=1)
    dsn_name = models.CharField(max_length=50)
    db_host = models.CharField(max_length=100, default='127.0.0.1')
    db_user = models.CharField(max_length=50, blank=False)
    db_pw = models.CharField(max_length=50, blank=False)
    db_name = models.CharField(max_length=50, default='test_db')
    db_type = models.CharField(
        max_length=25, choices=DATABASE_TYPES, default='oracle')
    db_param = models.CharField(max_length=500, blank=True)
    db_port_no = models.IntegerField(default=3306)
    dsn_status = models.BooleanField(default=False)

    def __str__(self):
        return self.dsn_name

    class Meta:
        ordering = ['project_name', 'dsn_name']


class Spname(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    project_name = models.ForeignKey(
        Project, on_delete=models.CASCADE, default=1)
    dsn_name = models.ForeignKey(
        DataSource, on_delete=models.CASCADE, default=1)
    report_name = models.CharField(max_length=100)
    sp_name = models.CharField(max_length=100)
    start_dt = models.CharField(max_length=50, blank=True, default='NULL')
    end_dt = models.CharField(max_length=50, blank=True, default='NULL')
    med_center = models.CharField(max_length=100, blank=True, default='NULL')
    result_table = models.CharField(max_length=50)
    additional_param = models.CharField(
        max_length=400, blank=True, default='NULL')
    priority_id = models.SmallIntegerField(default=1)
    is_active = models.CharField(max_length=1, choices=Y_N, default='Y')
    job_type = models.CharField(
        max_length=25, choices=DATABASE_OBJECT_TYPES, default='Stored_Proc')


class Tbllist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    project_name = models.ForeignKey(
        Project, on_delete=models.CASCADE, default=1)
    dsn_name = models.ForeignKey(
        DataSource, on_delete=models.CASCADE, default=1)
    table_name = models.CharField(max_length=100)
    result_table = models.CharField(max_length=100)
    table_type = models.CharField(max_length=1, default='T')
    priority_id = models.SmallIntegerField(default=1)
    import_utility = models.CharField(max_length=50, default='sqoop')
    custom_cmd = models.CharField(max_length=500, blank=True)
    additional_param = models.CharField(max_length=400, blank=True)
    ## etl_sch_time = models.CharField(max_length=100)
    ## execution_flag = models.CharField(max_length=1, default='Y')
    is_active = models.CharField(max_length=1, choices=Y_N, default='Y')
    job_type = models.CharField(
        max_length=25, choices=DATABASE_OBJECT_TYPES, default='Table')

    def __unicode__(self):
        return self.table_name

    class Meta:
        ordering = ['project_name', 'dsn_name', 'table_name', 'table_type']


class Script(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    project_name = models.ForeignKey(
        Project, on_delete=models.CASCADE, default=1)
    job_name = models.CharField(max_length=100)
    script_path_name = models.CharField(max_length=500, blank=False)
    additional_param = models.CharField(max_length=500, blank=False)
    priority_id = models.SmallIntegerField(default=1)
    is_active = models.CharField(max_length=1, choices=Y_N, default='Y')
    job_type = models.CharField(
        max_length=25, choices=DATABASE_OBJECT_TYPES, default='Shell_Script')

    def __unicode__(self):
        return self.job_name

    class Meta:
        ordering = ['project_name', 'job_name', 'script_path_name']


class Jobflow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    project_name = models.ForeignKey(
        Project, on_delete=models.CASCADE, default=1)
    jobflowname = models.CharField(max_length=50, unique=True)
    max_num_of_threads = models.SmallIntegerField(
        blank=False, null=False, default=5)
    is_active = models.CharField(max_length=1, choices=Y_N, default='Y')

    def __unicode__(self):
        return self.jobflowname

    class Meta:
        ordering = ['jobflowname']


class Jobflowdetail(models.Model):
    jobflowname = models.ForeignKey(
        Jobflow, on_delete=models.CASCADE, default=1)
    project_job_name = models.CharField(
        max_length=50, blank=False, default='job_name_alias_name')
    job_name = models.CharField(max_length=50, blank=False, default='job_name')
    job_type = models.CharField(
        max_length=25, blank=False, default='Stored_Proc')
    object_id = models.IntegerField(default=1)
    additional_param = models.CharField(max_length=300, blank=True, default='')
    ## etl_sch_time = models.CharField(max_length=100, default='')
    priority_id = models.SmallIntegerField(default=1)
    is_active = models.CharField(max_length=1, choices=Y_N, default='Y')

    def __unicode__(self):
        return self.job_name

    class Meta:
        ##unique_together = ('jobflowname', 'job_name',)
        ordering = ['job_name']


os.environ.setdefault("DJANGO_SETTINGS_MODULE", "pydataflow.settings")
activate(settings.TIME_ZONE)


def get_time():
    # return timezone.localtime(timezone.now())
    activate(pytz.timezone('America/Los_Angeles'))
    return timezone.localtime(timezone.now()) - timezone.timedelta(minutes=420)


class Processlog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    project_name = models.ForeignKey(
        Project, on_delete=models.CASCADE, default=1)
    jobflowname = models.ForeignKey(
        Jobflow, on_delete=models.CASCADE, default=0)
    jobflowdetail = models.ForeignKey(
        Jobflowdetail, on_delete=models.CASCADE, default=0)
    project_job_name = models.CharField(
        max_length=50, blank=False, default='job_name_alias_name')
    process_id = models.IntegerField(default=1)
    job_name = models.CharField(max_length=50, blank=False, default='job_name')
    job_type = models.CharField(
        max_length=25, blank=False, default='Stored_Proc')
    object_id = models.IntegerField(default=1)
    additional_param = models.CharField(max_length=300, blank=True, default='')
    status = models.CharField(max_length=10, blank=True, default='Success')
    # , format="%Y.%m.%dT%H:%M:%S%z"
    start_time = models.DateTimeField(default=timezone.now)
    end_time = models.DateTimeField(auto_now=True, null=True)
    logfile = models.CharField(max_length=500, blank=True, default='')
    log_url = models.CharField(max_length=100, blank=True, default='')
    pid = models.IntegerField(default=0)
    executed_job_names = models.CharField(
        max_length=800, blank=True, default='')
    execution_type = models.CharField(max_length=1, default='S')

    class Meta:
        ordering = ['process_id', 'status']


class Sch(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    project_name = models.ForeignKey(
        Project, on_delete=models.CASCADE, default=1)

pydataflow/pydataflow/sch/models.py
from django.db import models

# Create your models here.

pydataflow/pydataflow/sch/templates/sch_archive/process_log.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Process_logs</title>

   <link href="{% static 'process_log/css/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'process_log/css/bootstrap4.min.css' %}" rel="stylesheet">



</head>


{% block content %}


<body>
<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-12">
      <h2>Process Logs</h2>
      <table id="myTable1" class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Telefone</th>
            <th>Gênero</th>
          </tr>
        </thead>
        <tbody>
          {% for person in person_list %}
            <tr>
              <td>{{ person.name }}</td>
              <td>{{ person.email }}</td>
              <td>{{ person.phone }}</td>
              <td>{{ person.get_gender_display }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

  </div>

  <hr>

</div> <!-- /container -->

{% endblock content %}

{% block js %}
<script src="{% static 'process_log/js/jquery-3.3.1.js' %}"></script>
<script src="{% static 'process_log/js/bootstrap.min.js' %}"></script>
<script src="{% static 'process_log/js/jquery.dataTables.min.js' %}"></script>

 <script src="{% static 'process_log/js/data3.js' %}"></script>

{% endblock js %}
</body>

pydataflow/pydataflow/sch/templates/sch_archive/sch_main_view.html
{# {% extends 'common/base_common.html' %} #}
{% extends 'common/base.html' %}
{% block title %}{{ project }}{% endblock %}
{% block projects_active %}active{% endblock %}
{% load crispy_forms_tags %}

{% block body %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div class="header">

{% include 'common/breadcrum.html' %}

 <!--Project Info -->
<!--
<div class="container-fluid tbllists-container">
 <div class="col-sm-12 col-md-12">
  <div class="panel panel-default">
    <div class="panel-body">
     <table class="table">
        <thead>
                <tr>
                <th>Project Name</th>
                <th>Email</th>
                <th>Etl Schedule</th>
                <th>Is active</th>
                </tr>
         </thead>
        <tbody>
                <tr>
                    <td>{{ project.project_name }}</td>
                    <td>{{ project.email_notification }}</td>
                    <td>{{ project.etl_sch_time }}</td>
                    <td>{{ project.is_active }}</td>
                    <td>

                       <form action="{% url 'sch:sch_wizard_generic' project.id jobflow.id 0 0 %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="project_id" value="{{ project.id }}" />
                        <button type="submit" class="btn btn-primary btn-sm btn-success">
                            <span class="glyphicon glyphicon-calendar"></span>&nbsp;Schedule Project
                        </button>
                        </form>
                    {% if project.etl_sch_time != '' %}
                        <form action="{% url 'sch:sch_remove_cron' project.id jobflow.id 0 0 %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="project_id" value="{{ project.id }}" />
                        <button type="submit" class="btn btn-primary btn-sm btn-warning">
                            <span class="glyphicon glyphicon-calendar"></span>&nbsp;Un-Schedule
                        </button>
                        </form>
                    {% endif %}

                    </td>

                </tr>

        </tbody>
    </table>
   </div>
  </div>
 </div>
</div>
-->



 <!--Project Info End-->

 <!--Flow Info -->
<div class="container-fluid tbllists-container">
 <div class="col-sm-12 col-md-12">
  <div class="panel panel-default">
    <div class="panel-body">
     <table class="table">
        <thead>
                <tr>
                <th>jobflow Name</th>
                <th>Email</th>
                <th>Etl Schedule</th>
                <th>Is active</th>
                </tr>
         </thead>
        <tbody>
                <tr>
                    <td>{{ jobflow.jobflowname }}</td>
                    <td>{{ jobflow.email_notification }}</td>
                  <!--  <td>{{ jobflow.etl_sch_time }}</td>  -->
                    <td>{{ jobflow.is_active }}</td>
                    <td>

                        <form action="{% url 'sch:sch_wizard_generic' project.id jobflow.id 0 1 %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="project_id" value="{{ jobflow.id }}" />
                        <button type="submit" class="btn btn-primary btn-sm btn-success">
                            <span class="glyphicon glyphicon-calendar"></span>&nbsp;Schedule
                        </button>
                        </form>
                    {% if jobflow.etl_sch_time != '' %}
                        <form action="{% url 'sch:sch_remove_cron' project.id jobflow.id 0 1 %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="project_id" value="{{ jobflow.id }}" />
                        <button type="submit" class="btn btn-primary btn-sm btn-warning">
                            <span class="glyphicon glyphicon-calendar"></span>&nbsp;Un-Schedule
                        </button>
                        </form>
                    {% endif %}

                    </td>
                </tr>

        </tbody>
    </table>
   </div>
  </div>
 </div>
</div>
 <!--Flow Info End-->

<!--jobflowdetail Info -->
<div class="container-fluid tbllists-container">
 <div class="col-sm-12 col-md-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <table class="table">
                <thead>
                    <tr>
                    <th>Job Flowname </th>
                    <th>Job Name</th>
                    <th>Job Type</th>
                    <th>Priority id</th>
                    <th>Etl Schedule</th>
                    <th>Is active</th>

                    </tr>
                </thead>
                <tbody>
                {% for job in jobflow.jobflowdetail_set.all %}
                    <tr>
                        <td>{{ jobflow.jobflowname }}</td>
                        <td>{{ job.job_name }}</td>
                        <td>{{ job.job_type }}</td>
                        <td>{{ job.priority_id }}</td>
                        <td>{{ job.etl_sch_time}} </td>
                        <td>{{ job.is_active }}</td>
                        <td>
                      <!-- add sch type 2 after job id-->
                        <form action="{% url 'sch:sch_wizard_generic' project.id jobflow.id job.id 2 %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="spname_id" value="{{ job.id }}" />
                            <button type="submit" class="btn btn-primary btn-sm btn-success">
                                <span class="glyphicon glyphicon-calendar"></span>&nbsp;Schedule
                            </button>
                        </form>
                    {% if job.etl_sch_time != '' %}
                        <form action="{% url 'sch:sch_remove_cron' project.id jobflow.id job.id 2 %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="spname_id" value="{{ job.id }}" />
                            <button type="submit" class="btn btn-primary btn-sm btn-warning">
                                <span class="glyphicon glyphicon-calendar"></span>&nbsp;Un-Schchedule
                            </button>
                        </form>
                    {% endif %}
                    </td>

                    </tr>

                {% endfor %}
                </tbody>
                </table>
        </div>
    </div>
</div>

</div>
<!--jobflowdetail Info End  -->

</div>

{% endblock %}

pydataflow/pydataflow/sch/templates/sch_archive/sch_sp_main_view.html
{# {% extends 'common/base_common.html' %} #}
{% extends 'common/base.html' %}
{% block title %}{{ project }}{% endblock %}
{% block projects_active %}active{% endblock %}
{% load crispy_forms_tags %}

{% block body %}

<div class="header">

{% include 'common/breadcrum.html' %}

 <!--Project Info -->
<div class="container-fluid tbllists-container">
 <div class="col-sm-12 col-md-12">
  <div class="panel panel-default">
    <div class="panel-body">
     <table class="table">
        <thead>
                <tr>
                <th>Project Name</th>
                <th>Email</th>
            <!--    <th>Etl Schedule</th>  -->
                <th>Is active</th>
                </tr>
         </thead>
        <tbody>
                <tr>
                    <td>{{ project.project_name }}</td>
                    <td>{{ project.email_notification }}</td>
                <!--    <td>{{ project.etl_sch_time }}</td>   -->
                    <td>{{ project.is_active }}</td>
                    <td>

                        <form action="{% url 'sch:sch_wizard_generic' project.id 0 %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="project_id" value="{{ project.id }}" />
                        <button type="submit" class="btn btn-primary btn-sm btn-success">
                            <span class="glyphicon glyphicon-calendar"></span>&nbsp;Sch Project
                        </button>
                        </form>

                        <form action="{% url 'sch:sch_remove_cron' project.id 0 %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="project_id" value="{{ project.id }}" />
                        <button type="submit" class="btn btn-primary btn-sm btn-warning">
                            <span class="glyphicon glyphicon-calendar"></span>&nbsp;Un-Sch Project
                        </button>
                        </form>


                    </td>

                   <td>
                    <a href="{% url 'meta:exe_sp_all' project.id %}"
                     class="btn btn-primary btn-sm btn-play" role="button">Execute</a>

                   </td>
                </tr>

        </tbody>
    </table>
   </div>
  </div>
 </div>
</div>
 <!--Project Info End-->

<div class="container-fluid tbllists-container">
 <!--Table Info -->
 <div class="col-sm-12 col-md-12">

<div class="panel panel-default">
    <div class="panel-body">
        <table class="table">
            <thead>
                <tr>
                <th>Report Name</th>
                <th>Stored Proc Name</th>
                <th>Etl Schedule</th>
                <th>Is Active</th>
                </tr>
            </thead>
            <tbody>
            {% for spname in project.spname_set.all %}
                <tr>
                    <td>{{ spname.report_name }}</td>
                    <td>{{ spname.sp_name }}</td>
                <!--    <td>{{ spname.etl_sch_time }}</td>   -->
                    <td>{{ spname.is_active }}</td>
                    <td>

                    <form action="{% url 'sch:sch_wizard_generic' project.id spname.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="spname_id" value="{{ spname.id }}" />
                        <button type="submit" class="btn btn-primary btn-sm btn-success">
                            <span class="glyphicon glyphicon-calendar"></span>&nbsp;Sch Table
                        </button>
                    </form>

                    <form action="{% url 'sch:sch_remove_cron' project.id spname.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="spname_id" value="{{ spname.id }}" />
                        <button type="submit" class="btn btn-primary btn-sm btn-warning">
                            <span class="glyphicon glyphicon-calendar"></span>&nbsp;Un-Sch Table
                        </button>
                    </form>

                </td>
                </tr>
            {% endfor %}
            </tbody>
            </table>
        </div>
    </div>
  </div>

</div>
</div>

{% endblock %}